rebar.config
src/ejabberd_auth.erl
src/ejabberd_auth_http.erl
src/ejabberd_config.erl
src/scram2.erl

In http_auth I had to modify the startup method. The supervision tree is slightly different but it shouldn't pose problems. I dunno why using the ejabberd_sup was causing issues, but I switched it to using direct start_links and there is still a supervisor in the chain, so it should be okay.

[#150015077] Fixing http auth and integrating it into ejabberd core

---

src/mod_muc_room.erl

Didn't remember we used muc sub.  So setting ownership upon receiving a MUC SUB
@aghchan 
@RuoanJi 
@kkaminski

[#156577214] Adding ownership upon mucsub request.

---

src/mod_muc_room.erl

Removing this so we do not run the forget_room which deletes the room from the DB
@mpope9 
@mattfoley

[#156664850] Save Muc Room in DB When Running destroy_room

---

src/mod_muc_room.erl

Joining a room is nested inside of the `add_online_user` in `add_user_presence(From, Packet, add_online_user(From, Nick, Role, StateData))` so I added the create room logic which checks if the room is in the DB and restores it from those configs or creates a new room entirely
@mpope9

[#156666629] Joining a Room will Create the Room When It Does Not Exist

---

src/mod_muc.erl
src/mod_muc_room.erl

Reverted changes yesterday as it caused chat to be broken and found in the logs that the methods were undefined, causing the server to crash. Added those methods to the export so mod_muc_room can use these methods from mod_muc
@mpope9 
@MattFoley

[#156666629] Create Room When Joining if it Does Not Exist

---

src/mod_muc_room.erl

After the last PR, saw that the `RMod:register_online_room` crashed the server - going to use the exposed one in `mod_muc` instead
@mpope9

[#156666629] Register Online Room After Creation

---

src/mod_muc_room.erl

Looking at `mod_muc`, after it registers the room it routes the packet to signal that the room was created, so will do the same here.
@mpope9 
@MattFoley

[#156666629] Send Signal that Room was Created

---

src/mod_mam.erl
src/mod_mam_sql.erl
src/mod_muc_room.erl

Querying DB when history is empty, and sending event that history has been retrieved. Added logs while I'm at it.
@mpope9 
@MattFoley

[#155907078] Reload Messages from MAM on Recreated Rooms

---

src/mod_muc.erl
src/mod_muc_mnesia.erl
src/mod_muc_riak.erl
src/mod_muc_room.erl
src/mod_muc_sql.erl

This PR is the start of persistent subscription lists.
Originally the plan was to save these in a blob, but then the issue arose that each time a user logged in we'd have to loop through the blob to see if appending was needed.  I have chosen to go with the multi row approach, because of this.
The SQL query ensures that only one entry per subscription.
Some background: each muc room is a process.  The 'muc manager' is its own process.  When a subscription request comes it, I create a hook for the muc manager.  The muc room calls the hook and the manager stores the result in the database.
Only implemented the sql, added error returns if other databases are attempted to be used.
Create a room with a friend.
Saw two rows were created.
Stopped the server.
Rows still exist.
Started the server. …

[#156709610] Feature add subscribers

---

src/mod_muc.erl
src/mod_muc_mnesia.erl
src/mod_muc_riak.erl
src/mod_muc_sql.erl

Subscriptions are now persistent and no longer reliant on the muc room being in memory.  A bug was created as a side effect where all of the subscribed rooms that a user is subscribed to are brought back into memory, possibly due to a different SDK call.  This exacerbates the issue of too many muc rooms residing in memory.  Will file a separate bug to fix this.
Much like the other PR the mneisa and riak implementations are not going to be completed, as they will not be used.
Tested using multiple registered muc rooms, including 1x1 and 1x1x1.  
@RuoanJi 
@MattFoley

[#156709589] Subscriptions retrieved and displayed

---

src/mod_mam_sql.erl

Tested with a room with more than 50 messages.  The 50 MOST RECENT messages are retrieved in current time sorted order.
@aghchan 
@MattFoley

[#157237109] Fixing the messages that are retrieved

---

include/message_type.hrl
include/skillz_message_type.hrl
src/mod_muc_room.erl

If the message type is included in the list of message types then only send to the user(s) who didn't send the message.
@aghchan 
@kkaminski

[#160483755] bug message type offline message flow check

---

src/mod_muc_room.erl

I did not include the third argument to this call.  See the messages going to the spool table now locally.
@aghchan 
@kkaminski

[#160483755] Fixing bad call to offline message

---

src/mod_muc_room.erl

This should effectively call mod_pottymouth before sending the packet to mod_push_skillz.
Basically hitting a bloom filter, so it should be pretty performant. 
@aghchan 
@kkaminski

[#162091837] Filtering messages before they go to push

---

build.sh
src/mod_admin_extra.erl

Before send_stanza would shoot a message through the router, which spins up a muc room to direct the message to the offline message module.
Instead of sending it through the router, I copied the logic found where a message is sent to be stored.  Now we go directly to MySQL and bypass spinning up a new room.
Once again, this is a bandaid to the larger muc memory issue.
Sending this stanza
```
./sbin/ejabberdctl send_stanza 5983820@chat.dev.skillz.com 5983817-5983820@conference.chat.dev.skillz.com "<message to='55983817-983820@chat.dev.skillz.com' from='5983820@conference.chat.dev.skillz.com/5983817' type='groupchat' id='1b5f966b-76d7-4617-b535-3d6c55dbf53b' xmlns='jabber:client'><skillz_sdk xmlns='xmpp:skillz'>       <avatar_url>https://cdn.qa.skillz.com/profile-pics/52319d0e-03fd-4786-8908 …
```

[ES-950] Fixing muc memory leak found with send_stanza

---

src/mod_admin_extra.erl

So I forgot a pathway.  In the `process_groupchat_message` in `src/mod_muc_room.erl` there is a call to `mod_mam` that archives the message, and appends two rows to the stanza before adding to the offline table (which then gets sent to ModPushSkillz).  ModPushSkillz was breaking because of this on QA.  SO, I'm adding that missing call.
I have to spoof being in a muc_room, because I didn't really see functionality that supports directly writing to mod_mam without being in a muc room.  I added a comment saying we should add it eventually, but it _probably_ won't break anytime soon, because we'd have bigger issues if we go changing our muc room settings so drastically.
I'll post example stanzaz from QA's offline message table and the ones I've now generated locally to show there isn't any …

[ES-950] Adjusting send_stanza flow to hit mod_mam

---

src/mod_admin_extra.erl

OK, I forgot under the hood we actually don't send to the user we include, but to the opposite user.  I guess I could make a PR in the server-api repo instead of this one, but I don't know if that will break more stuff.  It looks like the correct user is inserted in the offline message table.
@Tdavis22 
@zgarbowitz

[ES-950] Offline messgaes sent to the correct user for send_stanza

---

src/mod_muc_room.erl

This should fix the broader memory leak.  Basically reusing what I wrote here, https://github.com/skillz/ejabberd/pull/57/files.  Also removing the code that isn't getting hit by the sdk.
I can't get the SOCKS proxy working anymore...so I'm not able to test locally
@Tdavis22 
@zgarbowitz

[ES-1437] Moving killing the muc from subscriptions to presence

---

src/mod_muc_room.erl

Made a wrapper function that kills mucs higher up in the call chain.
Please note that I can't test this due to lack of local proxying, and there are 3 other functions where this issue can be happening.  If this issue persists, I can make another PR for the different functions.
This is because force closing the sdk re-opens rooms.
Left a note to remove this and add a module that cleans mucs periodically. 
@zgarbowitz 
@matlegit

[ES-1437] Kill mucs higher up in the call chain

---

src/mod_muc_room.erl

Basically the configs passed to this function are never saved to the DB.  I'm not sure why this is a noop currently?  But this seems to work.
NOTE: This doesn't _really_ work locally unless the debugger is running, but I see that some debug logging that I have removed are being printed when I hit the ejabberdctl.  So I think some code isn't being purged locally, very strange behavior.  I want to test this further on QA to see if I have an issue with my local setup.
Local testing:
```
./sbin/ejabberdctl create_room 11 conference.chat.dev.skillz.com chat.dev.skillz.com
./sbin/ejabberdctl change_room_option 11 conference.chat.dev.skillz.com title 'test1'
```
Then check the database, the title is changed.
Run this and see the title is changed:
```
./sbin/ejabberdctl get_room_options 11 …
```

[ES-1307] Changing the change_room_option to persist changes

---

sql/2019-03-04-17-to-19-upgrade.sql

SQL migration for the upgraded version of ejabberd.  Ran locally without error.  The only issue is that this'll run an alter table statement on prod with 3.4m rows.  Might need to communicate with CA to have the mods announce a planned chat outage? Or maybe just pop it off....
Note, should we consider making a read replica for ejabberd?  We'd probably have to do some heavy modification to support it.
@Tdavis22 
@zgarbowitz

[ES-1545] SQL migration file to upgrade ejabberd to 19.02

---

src/mod_muc_room.erl

The top level function call that I added here: https://github.com/skillz/ejabberd/pull/79 was a bad idea.  We added it because I was having trouble with my local setup and couldn't actually connect.  What this did was create a 'race condition' of sorts appear _way_ more frequently.  It only happens 1% of the time on prod, going to file a different bug for that issue.
Connecting locally and setting break points, I see that the SDK is tearing down TCP connections differently(?).  This causes ejabberd to broadcast a message to all mucs that were connected to in the session once the SDK is force closed.  An unavailable presence is what is being broadcasted, but it wasn't hitting the previous logic added here: https://github.com/skillz/ejabberd/pull/78 , because the user is 'offline' at this …

[ES-1616] Fixing room creation issue and killing muc on all unavailable presences

---

src/mod_admin_extra.erl

When the send_stanza was called with the code we added to fix the memory leak, it didn't actually appear in an active process's room.  It would only show up in offline messages.
Check if the room exists.  If it does, call the old code path.
This won't result in a process leak, as the new code path doesn't bring a room up, and the old code path is only active when someone is in a room.  When that person leaves then the room will be cleaned up.
Two devices connected locally.  Challenging someone shows a correctly rendered message in the room.
@Tdavis22 
@zgarbowitz

[ES-1517] Bug online send stanza

---

mix.exs

So I am seeing these in the logs in QA after the `19.02` upgrade:
```erlang
2019-03-13 20:43:34.906 [error] <0.202.0> got unexpected info: {'EXIT',#Port<0.2518>,noproc}
2019-03-13 20:43:35.310 [error] <0.202.0> got unexpected info: {'EXIT',#Port<0.2519>,noproc}
2019-03-13 20:43:36.065 [error] <0.202.0> got unexpected info: {'EXIT',#Port<0.2520>,noproc}
2019-03-13 20:43:36.497 [error] <0.202.0> got unexpected info: {'EXIT',#Port<0.2521>,noproc}
2019-03-13 20:43:36.853 [error] <0.202.0> got unexpected info: {'EXIT',#Port<0.2522>,noproc}
2019-03-13 20:43:37.679 [error] <0.202.0> got unexpected info: {'EXIT',#Port<0.2523>,noproc}
2019-03-13 20:43:37.742 [error] <0.202.0> got unexpected info: {'EXIT',#Port<0.2524>,noproc}
2019-03-13 20:43:38.061 [error] <0.202.0> External eimp process …
```

[ES-1631] Fixing eimp in unupdated mix file

---

sql/2019-03-13-transform-subscription-table.sql

It looks like the work to actually use the `muc_room_subscription` table has been more or less done.  So this sql is to move all of our records from the `subscription` table to the `muc_room_subscription` table.
That string is a constant value that is provided.  Several steps of string processing is done during this query.  The table will not have data being written to it while we're draining it.
@Tdavis22 
@zgarbowitz

[ES-1631] Transform subscription table

---

sql/2019-03-13-transform-subscription-table.sql

Realized the old migration didn't deal with duplicates, and there is a unique index on one of the columns.  So if there is overlap then this would error out and won't run.
EDIT: What this does is noop on duplicate keys by inserting the constant value.  Using Insert Ignore causes all errors to be treated as warnings (is what I believe I read last week), and we would still want this to error in any other case.
@Tdavis22 
@zgarbowitz

[ES-1694] Adjusting the subscription migration to deal with overlap

---

src/mod_muc_room.erl

This line was omitted during merge conflict resolution.  Which was the main memory leak fix 🤷‍♂️ 
@Tdavis22 @zgarbowitz

Adjusting preivous merge confict resolution

---

src/mod_muc_room.erl

Chat is now OTA.  I guess Cobalt Plus and below it isn't.  So games on those SDKs have the old code that has issues which hit this code branch last.
Seeing this in QA
```bash
[ejabberd@islay-ejabberd-i-0ca5c2447e09098bc ~]$ ./sbin/ejabberdctl muc_online_rooms global
1688@conference.chat.qa.skillz.com
[ejabberd@islay-ejabberd-i-0ca5c2447e09098bc ~]$ ./sbin/ejabberdctl muc_online_rooms global
1688@conference.chat.qa.skillz.com
5974475-5983801@conference.chat.qa.skillz.com
5978567-5983801@conference.chat.qa.skillz.com
5983800-5983801@conference.chat.qa.skillz.com
5983801-5983808@conference.chat.qa.skillz.com
5983801-5983820@conference.chat.qa.skillz.com
5983801-5998750@conference.chat.qa.skillz.com
```
Basically the moment you join a room, every room you have becomes active.  Force closing …

[ES-1890] Re-adding previously removed memory leak fix

---

src/mod_admin_extra.erl

The http api `send_stanza` endpoint consistently returns 1 instead of 0.
If you look at the code, there are two paths that can be taken, one ends with:
`ejabberd_router:route(xmpp:set_from_to(Packet, From, To))`
and the other ends with
`ejabberd_hooks:run_fold(offline_message_hook, LServer, {bounce, PacketToSend}, [])`
These two functions have different return values.  The first code path is pre-memory leak fix.  Its return value is this:
`-spec route(stanza()) -> ok`
While the new code path's return value is this:
`-spec run_fold(atom(), any(), list()) -> any().`
Have send stanza return `ok`.
I saw a 'failed' nudge in game play and reproduced it using this command:
```
./sbin/ejabberdctl send_stanza 21951872@chat.qa.skillz.com 21579669-21951872@conference.chat.qa.skillz.com "<message …
```

[ES-1950] Changing send_stanza's return value

---

src/ejabberd_c2s.erl

Pushes aren't being sent.
```
2019-04-07 23:07:02.732 [error] <0.19456.153>@ejabberd_hooks:safe_apply:384 Hook roster_out_subscription crashed when running 'Elixir.ModPushSkillz':on_roster_out_subscription/1:     
** Reason = {error,undef,[{'Elixir.ModPushSkillz',on_roster_out_subscription,[{presence,<<"2dd2daa1-f596-414f-81db-2a64fbcb210d">>,subscribe,<<"en">>,{jid,<<"24788539">>,<<"chat.skillz.com">>,<<"498539436786344146026476322">>,<<"24788539">>,<<"chat.skillz.com">>,<<"498539436786344146026476322">>},{jid,<<"24083080">>,<<"chat.skillz.com">>,<<>>,<<"24083080">>,<<"chat.skillz.com">>,<<>>},undefined,[],undefined,[{xmlel,<<"player">>,[{<<"xmlns">>,<<"skillz:presence">>}],[]}],#{ip => {172,16,3,27}}}],[]},{ejabberd_hooks,safe_apply,4,[{file,"src/ejabberd_hooks.erl"},{line,381}]},{ejabbe …
```

[ES-2054] Fixing roster_out_subscription call

---

src/mod_muc_room.erl

Okay, so I see this line was changed in the latest version of ejabberd.  I saw here: https://github.com/skillz/ejabberd/blob/development/src/mod_admin_extra.erl#L1483 that we had it as a different function call before.  The code linked is supposed to emulate this code, but this code has changed.  This is why nudges work, but chat DMs don't.  
I can't test pushes locally, but I am able to reproduce the errors on QA/Staging/Production on my local setup.  With this new code I don't see the errors locally.
I'm going to use QA to test actual pushing functionality.
Asked processone if this was cool to do here, but I'm sure its okay
https://support.process-one.net/browse/EJABS-3299
@dawsonz17 
@zgarbowitz

[ES-2054] Reverting wrap function in mod_muc_room

---

src/mod_admin_extra.erl

When trying to mute a user, an error is being returned to the SDK.
Previously ejabberd was using the `kick_session` function call for this.  NOW it uses `kick_sessions` function call.
The `kick_sessions` function has a bug when interacting with the http api module.  The module expects functions to return `ok`, but `kick_sessions` returns a list of return values as it now scans over every possible session for a user.  So it'd return a `[ok, ok, ok]` if there were 3 sessions that were successfully terminated.
What the fix actually does is loop over the returned list, and filter out all `ok` values.  If any values remain, that means `kick_sessions` has an error and not all sessions have been kicked.  If the list is empty, then we return `ok`, as thats what http api module is expecting. …

[ES-2097] Fixing newer kick_session endpoint

---

src/mod_muc_room.erl

I believe this code got mangled during the upgrade.
Previous results: `416 Ok, 171 Failed, 853 Skipped of 1440` in `1303.445s`
After this PR: `500 Ok, 100 Failed, 840 Skipped of 1440` in `407.516s`!!!!
83 more tests in like half the time 😃 
@dawsonz17 
@zgarbowitz 
@hacctarr

[ES-2223] Fixing change config (for CT tests)

---

mix.exs
mix.lock
rebar.config
src/mod_muc_room.erl

Adding `meck` back for future tests.
Status is now:
`532 Ok, 68 Failed, 840 Skipped of 1440` in `324.374s`.
32 more tests passing.
This change was intentionally made.  Will do some local testing to confirm if this is actually what we want.

[ES-2224] Fixing more ct tests around ownership issues

---

test/muc_tests.erl

This line:
```
true = lists:member(201, Codes),
```
Checks to see if the room is a `new_room`.  WE don't care about that because we preserve rooms and never want a room thats existed before to be new, so removing this is safe because we've changed the use case.
This changes the config to persistent.
```
case ?config(persistent_room, Config) of
true ->
[104] = set_config(Config, [{persistentroom, true}], Room),
ok;
false ->
ok
end.
```
and the code below changes it to not persistent.
WE don't care about this, because we want our rooms to always persist, but we actually delete them.  They're data persistent but not process persistent.
`595 Ok, 3 Failed, 842 Skipped of 1440` in `282.318s`
This fixes 65 tests and shaves off more time.
@hacctarr 
@dawsonz17 
@zgarbowitz

[ES-2224] Fixing CT tests related to persistance and 'new_room'

---

test/muc_tests.erl

This fixes the remaining test.
`599 Ok, 0 Failed, 841 Skipped of 1440` in `370.832s`
Woot.
@dawsonz17 
@zgarbowitz 
@hacctarr

[ES-2220] Fixing subscription tests - final ct test fix.

---

sql/2019-05-02-remove-outbound-friend-requests.sql

During this P0: https://skillzinc.atlassian.net/browse/ES-2123 friends requests couldn't go through to users.  The following SQL clears this bad data and friends requests during the time of the bug being reported and resolved will be cleared out.
Ran successfully of staging and QA and two accounts who had outstanding friends requests that couldn't be accepted were able to re-send the requests and actually complete the friend request process.
@hacctarr 
@zgarbowitz 
@dawsonz17

[ES-2257] SQL to remove bad friends requests during previous bug

---

.gitignore
lib/mix/tasks/ct.ex
mix.exs

We are going to be using mix under the context of a child app in an umbrella project.  This PR does that, and fixes the `ct` task to reflect its new position.  
`     child_cwd = "#{cwd}/apps/ejabberd" # TODO: kind of a hack.  this should be fixed forsure.`
This is a slight hack that I don't know how to fix.  Its not the most awful thing in the world, but if we change the directory structure then it'll be a hassle.
`File.mkdir("#{child_cwd}/ebin")` is needed because ct complains that there needs to be a local ebin directory, even though it runs with it being empty.
@hacctarr 
@dawsonz17

[ES-2221] Updating mix for umbrella child

---

src/ejabberd_auth.erl
src/ejabberd_config.erl

Roster (eg friend requests) isn't working.  This is because auth is failing for a second user.  this could be because we are mixing internal auth and external auth (eg authing inside of ejabberd and authing against TS) because cas isn't an actual user.  This mixing is causing actual user auth to fail, preventing friend requests from actually going through.
The coded added is emulating this pr that was not included in the 19.02 upgrade because it is hacky: https://github.com/skillz/ejabberd/commit/0f3c9dcb12e265b5582e957c70bfc7bd799c6b41
Going to try it out and investigate a better way of doing auth after.
@hacctarr 
@dawsonz17

[ES-2614] Adding back auth hacks temporarily

---

sql/2019-05-02-remove-outbound-friend-requests.sql

This sql will now delete rosters from when the initial friend request P0 came in to the present day.
@hacctarr 
@dawsonz17

[ES-2614] Adjusting sql to delete invalid roster states

---

mix.exs

We are in a hybrid state where ejabberd can either be in an umbrella, OR be stand alone (our current official build process).
To prevent build fails for the primary build mechanism I'm adding a check that looks for the umbrella config file.  Otherwise, use the old, ejabberd config.
@hacctarr 
@dawsonz17

[ES-2230] Fixing mix error with config path

---

mix.exs
test/ejabberd_SUITE_data/ejabberd.yml

Changing this to use more recent certfile configs and also adjusting logger to use the Elixir Logger instead of lager, as it seems tests become unhappy with just lager.
@hacctarr 
@dawsonz17

[ES-2230] Updating test .yml to use updated certfile options

---

mix.exs
test/ejabberd_SUITE_data/ejabberd.yml
test/suite.erl

Okay, the issue before is that when running from the chat-service these config values did not have the correct path, they'd look under `chat-service/ca.pem` for example, instead of `chat-service/logs/xxx/ca.pem`.  Now we are going to use the actual ca.pem and cert.pem file path and use previously utilized substitution methods to take care of this.
@dawsonz17 
@hacctarr

[ES-1637] Adjusting cert configs to use fully qualified paths

---

include/mod_muc_room.hrl
sql/2019-07-26-19-user-affiliation-table.sql
src/mod_muc.erl
src/mod_muc_mnesia.erl
src/mod_muc_room.erl
src/mod_muc_sql.erl
test/docker/db/mysql/initdb/mysql.sql

This PR adds support for persisting global server-side mutes and bans.
Some small background is that Ejabberd has built-in support for persisted banning via the `Outcast affiliation`, and built-in support for muting (although it is not persisted) via the `visitor role`. These are both stored in the StateData of each muc_room, which is counter-intuitive to our platform. We would like bans/mutes to be persisted and global.
This was accomplished by:
1. Adding a new sql table called user_affiliation, which maps user_id -> affiliation
2. Adding an ets_cache to quickly fetch the affiliation for any user, warmed at startup from the sql table. 
3. Adding a new affiliation called `muted` so that we can persist mutes
4. Assigning a user role to `visitor` when joining a room if their affiliation is …

[PS-6075] Add server side mute/ban and a global affiliation table

---

src/mod_muc_room.erl

Locally, my XMPP client is auto kicked when affiliation is changed to outcast.
When testing on QA, I discovered that the SDK does not auto-kick, and this bug originated by users seemingly avoiding the kick_session command. 
This ensures that if the user is banned/muted, but somehow manages to stay in the room, they at least will be set to visitor and cannot talk. 
My previous solution was to only set the role on room join, but if the user is already in a room and avoids the kick, they were able to talk still when muted/banned
@mpope9 @aghchan @arlene-enero

[PS-7793] Set role to visitor on outcast affiliation change

---

src/mod_muc_room.erl

I did not properly return the result of set_role in my last PR, as set_role does not actually do anything besides return an updated StateData.
I have found a cleaner way, however, because by default the role gets set to none when a user is outcasted. Instead, we can set to visitor at that point. That value is passed in as StateData to set_affiliation, and subsequently returned.
I was able to test this locally by commenting out the send_kickban_presence (which is respected by my XMPP client but ignored by the SDK) so that I could stay in the room and show that I am a visitor that cannot speak
@mpope9 @aghchan @arlene-enero

[PS-7793] Set role to visitor when affiliation changed to outcast

---

src/mod_muc_room.erl

For context this was not able to be tested before because DMs were broken in general due to a permission issue. After fixing that issue, I discovered 1 more issue:
If a user has created a DM, they can no longer be banned/muted by skillz-cas
This is because there is a line that restricts decreasing the affiliation of owners.
Because we allow users to create their own MUC rooms, and each user must be an owner of their own MUC room in order to create the room, any user that creates a DM (or group chat) will be considered an owner.
This fix is to ensure that skillz-cas has the ability to decrease the affiliation of users that have created DMs
@david-thornton717

[PS-7793] Enable decreasing owner affiliation

---

src/mod_muc_room.erl

Adding logging to each fail case of can_change_RA to identify which case is failing when banning a user that has created a DM. After finding which case fails, I will adjust it accordingly
Will revert this when no longer needed
@mpope9 @leejona16

 [PS-8252] Add logging to detect when can_change_RA fails

---

src/mod_muc_room.erl

Added logs at each point along the path where can_change_ra failed, and found that when a user has created a DM and is the owner, this is the point where it fails.
I have left the logs in the other fail cases in case they still fail after setting this to true.
@mpope9 @leejona16

[PS-8252] Enable adjusting affiliation for users that have created a DM

---

src/mod_muc.erl
src/mod_muc_room.erl
src/mod_muc_sql.erl

Context: Realized that the ets_cache in use here is node-specific.
I began adding logic to fallback to sql on cache miss, but then I realized that the following scenario would break it:
1. cas connects to chatbox1
2. cas bans user on chatbox1
3. cas DCs and connects to chatbox2
4. cas unbans user on chatbox2
5. cas DCs and connects to chatbox1
6. cas now believes that the user is banned because chatbox1 still has the banned affiliation in the cache. It will not be a cache miss, so the fallback would not save us here
The long-term solution is to use a distributed cache. The options here are Mnesia or Redis, where I'm leaning toward using mnesia with sync writes for bans, dirty_writes for unbans. I have a story in the backlog to fix this
In the meantime, we simply always hit the sql table. …

[PS-8252] Remove local affiliation cache

---

.dockerignore
Dockerfile
kubernetes/base/deployment.yaml
kubernetes/base/kustomization.yaml
kubernetes/base/namespace.yaml
kubernetes/base/secret.yaml
kubernetes/base/service.yaml
scripts/create_users.sh
scripts/run.sh

Added kubernetes manifests for ejabberd/chat service.
Chose a single replica deployment over a statefulset because we'll be setting up the mnesia database as an external resource in a future pull request. It's not worth our time to temporarily create a statefulset and then completely shift over to deployment later.
Added a script that automatically creates users in ejabberd if you pass the information in via environment variable. Format is `myuser@domain:mypassword anotheruser@anotherdomain:mypassword`.
Confirmed that an XMPP client (Spark) on the desktop was able to connect to the chat service running in minikube. You just have to go to advanced setting, uncheck "Automatically discover host and port", and then put in the host and port that `minikube service` gives you. That host and port …

Feature add kubernetes

---

Dockerfile
kubernetes/base/config/access-control-lists.yml
kubernetes/base/config/access-rules.yml
kubernetes/base/config/api-permissions.yml
kubernetes/base/config/ejabberd.yml
kubernetes/base/config/ejabberdctl.cfg
kubernetes/base/config/hosts.yml
kubernetes/base/config/inetrc
kubernetes/base/config/listen.yml
kubernetes/base/config/log.yml
kubernetes/base/config/modules.yml
kubernetes/base/deployment.yaml
kubernetes/base/kustomization.yaml
kubernetes/base/secret/authentication.yml
kubernetes/overlays/qa/config/access-control-lists.yml
kubernetes/overlays/qa/config/hosts.yml
kubernetes/overlays/qa/kustomization.yaml
kubernetes/overlays/qa/secret/authentication.yml
kubernetes/overlays/staging/config/access-control-lists.yml
kubernetes/overlays/staging/config/hosts.yml
kubernetes/overlays/staging/kustomization.yaml
kubernetes/overlays/staging/secret/authentication.yml

Added configuration overlays by leveraging configMapGenerator from kustomize. This solves the problem of making sure a change to the configmap triggers a rolling update and allows us to overlay files on top of each other for different environments.
Had to modify the Dockerfile as well, as it turns out that ejabberd doesn't like where I put the ejabberd modules. It wants those in the home directory of the user that's running the node. We may be able to change that later via configuration options but I didn't see a quick and way to do so.
@thePhilGuy

[ES-4115] Added configuration overlays to the kubernetes manifests

---

Dockerfile

Added a section to the dockerfile for running tests for mod_push_skillz. Other modules either had failing tests (mod_beam_stats) or try to start running themselves during the test (mod_pottymouth).
Removed the global `MIX_ENV` since it's not actually useful.
Ejabberd itself doesn't have any tests that get run in Jenkins, so I didn't dig any deeper. Unfortunately that was all I could accomplish in the timebox.
@thePhilGuy

[ES-4113] Added test execution for mod push skillz

---

src/mod_mam_sql.erl

Hardcoding the result of the count(*) to 50. 
This breaks the ability to do ResultSet paging on MAM commands, however we do not make use of MAM for any purpose and there is no reason to support getting the middle of the archive for our use case.
count(*) on a table with 7m rows was taking over 12s on my local. In prod this table has >=16m rows and will be even worse.
By hardcoding it to 50, the query is now more like ~10ms.
We only query from the lastPage from CAS, and usually with a limit of 5. 
The value of 50 is mostly arbitrary but it allows for us to grab a larger limit later if necessary. 
@aghchan @TomPeng19971208

[PS-4816] Speed up MAM query by removing the use of count(*) on archive table

---

src/mod_offline_sql.erl

We have been assuming that "offline" messages function as "unread" messages. By design, when you first connect to ejabberd, all offline messages are cleared in the DB. This gives you time to display the fact that you have offline messages, and the next time you login they are gone. 
We want them to act as "unread" messages, which means that we do not clear them until explicitly told by the SDK that the messages have been viewed.
The SDK asks us to remove offline messages at the time of joining a room - DMs, group chats, etc. 
This will now actually act as "unread" messages as we expect!
@aghchan @TomPeng19971208

[PS-12438] No longer remove offline messages on new presence

---

kubernetes/overlays/staging/service-external.yaml
kubernetes/overlays/staging/service-internal-administration.yaml

```
kubectl exec -n server chat-service-0 -c ejabberd -it -- /opt/chat-service/sbin/ejabberdctl list_cluster
```
Returns
```
'ejabberd@chat-service-2.chat-service-internal.server.svc.cluster.local'
'ejabberd@chat-service-1.chat-service-internal.server.svc.cluster.local'
'ejabberd@chat-service-0.chat-service-internal.server.svc.cluster.local'
```
There is a VPC peering connection that allows:
- ejabberd pods in kubernetes VPC to reach mysql in legacy VPC
- ejabberd pods in kubernetes VPC to reach rabbitmq in legacy VPC
- ejabberd pods in kubernetes VPC to reach API Gateway in legacy VPC
- chat-admin-service in legacy VPC to reach service-internal-administration load balancer
- user-details-service in legacy VPC to reach service-internal-administration load balancer
Examples here are from …

[ES-5609][kubernetes/staging] Cutover DNS records for staging load balancers

---

kubernetes/base/config/api-permissions.yaml

I had previously whitelisted using puppet-ejabberd (still necessary for production). However, we use Kubernetes now in our QA/Staging environment, which no longer uses puppet.
Instead we need to whitelist via the Kubernetes configs
@aghchan @gschnaubelt

[PS-15768] Whitelist rooms_unused_destroy endpoint

---

src/mod_admin_extra.erl
src/mod_muc_room.erl

Background:
There is currently a bug where we send double push-notifications for chat-events. This only occurs when a user is "offline" and "not in the room" and then sends a DM to a room. For example, when accepting a friend request (which you do while not in a room), we automatically send "Thanks for adding me" as a chat message to the person that was added. This triggers a push-notification for BOTH users, including the user that sent the "thanks for adding me message". 
Another way to consistently trigger this is to send a chat message from the friends list by clicking on their avatar, rather than entering the chat room.
Matt had actually implemented logic to handle this case, but it is a little bit complicated for what it's doing and assumes that the only ignorable types are nudges …

[PS-15155] Remove filtering offline_messages by message_type

---

mix.exs

```
ERROR: sh(git clone -n git://github.com/dvv/base64url.git base64url)
failed with return code 128 and the following output:
Cloning into 'base64url'...
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
This dep is relying on the git protocol. We should instead query using https like the other dependencies by forcing it here

Use updated git url for base64url dep

---

mix.exs
rebar.config

* Use updated git url for base64url dep in Rebar
* Update rebar.config
* Update mix.exs

Use updated git url and tag for base64url dep in Rebar and Mix (#176)

---

src/mod_block_incoming.erl
src/mod_mam_sql.erl
src/mod_offline_sql.erl
src/mod_privacy_sql.erl
src/mod_roster_sql.erl
src/mod_vcard_sql.erl

Direct more read-only queries to replicas. None of these queries are used in explicit transactions that would both read/write. This means they are safe to direct to the replicas bc there is no implied logic requiring that a read should be guaranteed to include something that was just written or that a row being read must be locked until some write completes. These queries also represent the next highest impact on the load of the primary MySQL Ejabberd database.
Along with the above, this PR includes extra logging and a longer command timeout for the mod_block_incoming module used to block friend requests to moderators.

[PS-58628] Direct More Read-Only Queries to Replicas

---

src/mod_vcard.erl

Using a warm cache is much faster than direct DB querying. On a cold cache, larger requests (~100+) is faster going direct to the DB. However, since we have increased cache size, we will almost always have a warm cache.

[PS-64994] Multi-vcard performance optimization

---

src/mod_muc_admin.erl

Currently, a single dead pid representing a room can halt the cleanup process for removing unused rooms. The pids are stored in the DB, so it could be that some error or another caused the pid to die before it could be removed from the DB properly. In this case, the job will fail to clean up that room and all others. This PR fixes that by checking if pids are alive and also safely wrapping the whole thing in a try/catch.

[PS-64548] Fix error in unused cleanup code

---

src/mod_muc_room.erl

fix user-role and avatar-url extraction in get-room-summary endpoint

Fix user-role and avatar-url extraction in get-room-summary endpoint
