skillz/ejabberd

README

updated README with instructions to copy ejabberd.yml

---

src/mod_muc_room.erl
src/mod_privacy.erl

[#151259942] Updating packet from and to

---

src/mod_muc_room.erl

This basically reverts 1 field change @thePhilGuy

still for the blocking issue. Trying to minimize the amount of changes

---

tsung.xml

adding it here, I couldn't get great performance doing the custom xml requests 10% of the time, 
`error_send_no_ws_connection` being the main error. Also the custom requests aren't 100% since a lot of them require parsing the responses which I'm not sure if tsung can do out of the box
http://buildz.skillz.com/job/TS/job/Gatling/job/TsungStagingtests/114/HTML_Report/report.html
@IRog

[#151810061] Add tsung.xml 

---

src/mod_metrics.erl

[#151926492] more accurate connected users CAS adds 2

---

src/ejabberd_c2s.erl

@freester1 
@thePhilGuy 
(for fixing notifications for friends from blocked users)

[#152552772] Updating code I put in before and think local test was working

---

src/xmpp_stream_in.erl

[#153324202] Added in update from P1 and catch-all in process_element

---

tsung.xml

@freester1 
I put it to 9. (I ran out of users in the csv, so when we get more we can go higher)

[#153525958] Updates to tsung for load testing

---

src/mod_admin_extra.erl
tsung.xml

Also upped tsung from awhile ago
@mpope9

[#154293031] Our resources seem to be uuids so Im just kicking all a users resources so we dont need to specify it

---

create-rooms.py
delete_rooms.py

Python script to create 5k rooms.  Python script to delete group messages and DMs
@aghchan 
@RuoanJi

[#155861133] Feature room deletion script

---

src/mod_muc_room.erl

Now we have members and owners.  NO ADMINS.  
@aghchan 
@RuoanJi

[#155861133] Fixing the ownership issue

---

src/mod_muc_room.erl

I think my change had effects that were unwanted
@aghchan 
@RuoanJi

[#155861133] Using correct syntax now

---

src/mod_muc_room.erl

EVERYONES AN OWNER NOW
@aghchan 
@RuoanJi

[#155861133] All members of a room are now owners.

---

src/mod_muc_room.erl

Didn't assign the variable.
@aghchan 
@RuoanJi

[#156577214] Assigning the state data that was changed

---

src/mod_muc_room.erl

Removing all instances of changing affiliation.  Now just allowing admins to do owner things where the error message appears.
@aghchan

[#156665132] Admin can create rooms

---

src/mod_muc_room.erl

[#156665132] Fixing reverse logic

---

src/mod_muc_room.erl

Reverts skillz/ejabberd#35 as it currently causes creating rooms to fail
@mpope9

Revert "[#156666629] Joining a Room will Create the Room When It Does Not Exist"

---

create_rooms.sh
room_removal.py

[#156699867] Adding scripts for creation and deletion

---

src/mod_muc_room.erl

Forgot to check if room is already in the muc_online_room before registering
@mpope9 
@MattFoley

[#156666629] Check if Room is in Mnesia Before Creating Room

---

src/mod_muc_room.erl

Handling case when not creating a room when joining
@mpope9 
@MattFoley

[#156666629] Added Default Case For Not Creating Room When Joining

---

src/mod_muc_room.erl

[#156666629] Add Logging for Creating Room when Joining

---

src/mod_muc_room.erl

Reverts skillz/ejabberd#43
@mpope9 
@MattFoley

Revert "[#156666629] Add Logging for Creating Room when Joining"

---

src/mod_muc.erl

[#156666629] Create Room When Joining if it Does Not Exist

---

src/mod_mam.erl
src/mod_mam_sql.erl
src/mod_muc_room.erl

Reverts skillz/ejabberd#51
Reverting for now, planning to move changes to when room is initialized. 
@mpope9 
@MattFoley

Revert "[#155907078] Reload Messages from MAM on Recreated Rooms"

---

README
build.sh

Updating readme and creating new build script.
@aghchan 
@kkaminski

[#156707894] Feature local development

---

src/mod_muc_room.erl

Now when we retrieve muc subscribers the room will not persist.  However, it is loaded into memory for a short amount of time.
This potentially fixes the other bug where muc rooms are persisted after the last user leaves.
@RuoanJi 
@MattFoley

[#156968485] Closes the room if no occupants exist

---

README

Adding links and displaying our most recent changes with links to the PRs.

[#156891847] Feature update docs

---

src/mod_mam_sql.erl
src/mod_muc_room.erl

Now using time archived instead of time retrieved.
@aghchan 
@MattFoley

[#157257017] Bug fix timestamps

---

src/mod_mam_sql.erl
src/mod_muc_room.erl

[#157257017] String to int fix

---

src/mod_mam_sql.erl
src/mod_muc_room.erl

Revering previous attempts and making less invasive approach.  Basically reverting everything to its previous state except the changes that I added.
@aghchan 
@MattFoley

[#157257017] Bug adjusting timestamp fix

---

src/mod_muc_room.erl

I misunderstood the timestamp format.  This should fix it.
@aghchan 
@MattFoley

[#157257017] Fixing timestamp format

---

src/ejabberd_sm.erl

Putting In the same logging as we do for pushes triggered via DMs
@mpope9

[#156360471] Feature Add Logging For Pushes In Global Chat Rooms

---

src/mod_muc_room.erl

Adding this to confirm values that determine whether to trigger pushes
@DTxCode 
@kkaminski

[#156360471] Feature Add Logging For Triggering Pushes

---

src/mod_admin_extra.erl

Instead of directly sending the message, now we shall push it through the offline message flow.
Can't test this locally, obviously.
@kkaminski 
@RuoanJi

[#159511907] Sending ejabberd messages through the offline flow

---

run.sh

[#161369242] updated ejabberdctl path

---

100_create_default_users.sh

one last update to ejabberdctl path

[#161369242] update ejabberdctl path

---

src/mod_admin_extra.erl

Re-adding the original logic when the room exists, because when a user is in a room and the current code is implemented, it doesn't go to the rooms history and the SDK looks weird.
@Tdavis22 
@zgarbowitz

[ES-1544] Adding option for send_stanza for online rooms

---

mix.exs

Straight from processone
@hacctarr 
@dawsonz17

[ES-2221] Commit from mainline to fix umbrella dep issues

---

src/mod_roster.erl

In a hail mary attempt, I'm adding debug logging to further diagnose the issue on QA.
@hacctarr 
@dawsonz17

[ES-2614] Adding debug logging to mod_roster

---

src/mod_roster.erl

At the advice of processone I'm adding more debug logging
@hacctarr 
@dawsonz17

[ES-2614] Adding more mod_roster debug statements

---

src/ejabberd_sm.erl
src/mod_roster.erl

[ES-2614] More logging around privacy lists, where processone suggested

---

src/ejabberd_sm.erl

[ES-2614] Fixing debug log compiler error

---

src/mod_privacy.erl

[ES-2614] Adding logging to mod privacy

---

src/ejabberd_sm.erl
src/mod_privacy.erl
src/mod_roster.erl

[ES-2614] Added even MORE logging to diagnose mod_roster

---

src/ejabberd_auth_http.erl

forgot a file in the revert.  idk what was actually done here besides changing the supervision tree, not alot of comments in the previous PR
@hacctarr 
@dawsonz17

[ES-2614] Adjusting ejabberd auth back to previous standard

---

src/ejabberd_auth.erl
src/ejabberd_auth_http.erl
src/ejabberd_config.erl

I added some code back from Ivy's previous PR that did not work.
@hacctarr 
@dawsonz17

[ES-2614] Reverting previous auth hack re-introduciton

---

src/ejabberd_sm.erl
src/mod_privacy.erl
src/mod_roster.erl

[ES-2614] Removing debug logging

---

test/docker/db/mysql/clear_test_data.sh
test/docker/db/mysql/initdb/mysql.sql
test/docker/docker-compose.yml

Docker mysql for tests.  See here https://github.com/processone/ejabberd/commit/e427358e089864955d033305ab1bc0c6baff3c24
@dawsonz17 
@hacctarr

[ES-2231] Mysql Docker for Testing

---

mix.exs

Now this build works both locally and in an umbrella
@dawsonz17 
@hacctarr

[ES-2231] Adjusting the now janky hybrid mix file

---

src/ejabberd_auth.erl

@hacctarr @dawsonz17 
Cherrypicking this from ejabberd 19.05

[ES-2759] Upgrading ejabberd auth module

---

rebar.config

@hacctarr 
@dawsonz17 
Insta merging dependency update.

[ES-2759] Ejabberd cache tab upgrade

---

src/ejabberd_auth.erl
src/ejabberd_auth_http.erl
src/ejabberd_sm.erl

Insta-merging logging for auth investigation.
@hacctarr 
@dawsonz17

[ES-2759] Investigating user_exists failures

---

src/ejabberd_auth.erl

@hacctarr 
@dawsonz17 
Insta merging logging changes.

More auth logging

---

src/mod_muc_room.erl

My recent change to use global affiliations does not work correctly with DMs, which require each participant to be owner/admin in their individual rooms. Of course we don't want to globally set users to be admins in order to allow them to join DM rooms.
The solution here is to detect if we are getting/setting an affiliation for a DM, which will contain a room of the name `nick1-nick2-nickX`, then we can fallback to the old method of getting/setting affiliations inside of the StateData record for this muc-room. 
The git Dif looks a little odd, but the logic is straight forward: (edit: actually doing hide white-space changes makes it very readable)
if room name contains a `-`, use existing fallback methods
if room does not contain a `-`, use current global affiliation cache/table logic …

[PS-7793] Fallback to old affiliation get/set for Group-chats (DMs)

---

src/mod_muc_room.erl

Just cleaning up logs from previous testing, as I believe the issue has been resolved
@mpope9 @leejona16

[PS-8252] Removing excess logs

---

kubernetes/base/config/api-permissions.yaml

We'll be using the get roster api endpoint to get friends for a user.
@bhickey-skillz 
@aghchan

[PS-11267] Open get_roster endpoint to api

---

kubernetes/base/chat-alertrule.yaml
kubernetes/base/config/statsd-mapping.conf
kubernetes/base/configmap.yaml
kubernetes/base/kustomization.yaml
kubernetes/base/service-internal-discovery.yaml
kubernetes/base/serviceMonitor.yaml
kubernetes/base/statefulset.yaml
src/mod_metrics.erl

fixed syntax with ejabberd metrics for prometheus

[ES-4122][ejabberd-metrics] fixed syntax with ejabberd metrics for prometheus

---

mix.exs

[PS-33038] Add aws extra applications

---

mix.exs

Revert "[PS-33038] Add aws extra applications"

---

src/ejabberd.app.src.in

Revert "[PS-33038] Add aws modules to ejabberd included apps"

---

README.md

Just need a new commit in here to troubleshoot some issues deploying to staging.  It's late in the day and this is just a readme change, so if this repo lets me merge this in once this PR is opened, I'm going rogue and merging it in.
@skillz/hyperion-server 
@bhickey-skillz

Noop readme change to troubleshoot a build issue

---

src/mod_muc_sql.erl

This is an equivalent query for get_subscribed_rooms that allows the MySql query engine more freedom in generating execution plans and results in fewer reads and CPU cycles for this query. In testing, the former query read ~15k rows per query and this new one reduces that to only 2 rows, which should help the scalability of this query.

PS-54792: Improved get_subscribed_rooms Query

---

src/mod_muc_sql.erl

Sweep 2022-01-10

---

src/mod_block_incoming.erl

Remove unnecessary message and offline message filtering. In my local testing for mod_block_incoming, we only need to auto-deny subscription requests. By removing the filters on messages, we will be much more efficient since subscription requests are a lot less common than messages. Also, export the is_blocking_user function for use in ModPushSkillz.

[PS-59196] Remove from mod_block_incoming unnecessary message and offline message filtering

---

src/mod_block_incoming.erl

We only need to filter subscript requests, not every message.

[PS-59014] Add logging and optimize blocking incoming

---

src/mod_vcard.erl

returns binary <<"Nickname">> if successful, else returns :none.

[PS-60980] Get Nickname from vCard

---

src/mod_block_incoming.erl
src/mod_vcard.erl

When requesting multiple vcards, if none are found, return an empty vCards xml el instead of the singular vcard-temp object that was returned before. When we return results from vCards (plural), we should always have that vCards node since that would be the expected response for empty, a single one found, and multiple found.
Also added a defensive guard against an empty list of usernames sent in, which will revert to the singular vcard-temp response.

[PS-61671] Better handling of empty vcards response

---

config/dev-api-permissions.yaml
config/dev-modules.yaml
src/mod_muc.erl
src/mod_muc_admin.erl
src/mod_muc_room.erl
src/mod_muc_sql.erl
src/skillz_util.erl

* amortized rooms_unused_destroy
* api for set_user_affiliation
* api for get_room_summary

[PS-64044] Merge development to master

---

src/mod_muc_admin.erl
src/mod_vcard.erl
src/skillz_util.erl
test/ejabberd_SUITE.erl
test/ejabberd_SUITE_data/ejabberd.yml
test/muc_tests.erl
test/skillz_tests.erl

* expand unit tests and add skillz specific unit tests
* further optimization of multi-request vcard method
* fix issue with dead pids preventing unused room cleanup

Dev to Master

---

config/dev-access-control-lists.yaml
src/mod_muc_admin.erl
src/mod_muc_room.erl
src/mod_vcard.erl
src/skillz_util.erl
test/skillz_tests.erl

* skillz-cas as admin in localhost
* vcard multi-fetch needs to be a list
*  send message resource extraction
* get room summary fix
* add avatar url to room summary

Multiple minor fixes

---

README.md
src/mod_muc_room.erl

fix user-role and avatar-url extraction in get-room-summary endpoint

Fix user-role and avatar-url extraction in get-room-summary endpoint
